#!/bin/bash
echo ""
echo "***************************************************************************************************************************************"
echo -e "                              To install Command Line Tools, run this ---> \033[1;31mxcode-select --install\033[0m"
echo "***************************************************************************************************************************************"
echo ""
echo -n  -e "\033[1;31mHave you installed Command Line Tools? \033[0;32m(y/n): \033[0m"
read -n 1 base
echo ""
if [ "$base" == "y" ]; then
	ruby -e "$(curl -fsSL https://raw.github.com/Homebrew/homebrew/go/install)"
	brew doctor
	brew tap phinze/homebrew-cask
	brew install wget
	wget https://raw.github.com/git/git/master/contrib/completion/git-prompt.sh -O ~/.git-prompt.sh
	wget https://raw.github.com/git/git/master/contrib/completion/git-completion.bash -O ~/.git-completion.bash
	brew install ack
	brew install brew-cask
	brew cask install google-chrome
	brew cask install lastpass-universal
	brew cask install firefox
	brew cask install vlc
	brew cask install alfred
	brew cask install dropbox
	brew cask install iterm2
	brew cask install skype
	brew cask install xquartz
	brew cask install shiftit
	sudo easy_install pip
	sudo pip install grip
	# no brew cask for MouseLocator
	wget --no-check-certificate http://www.2point5fish.com/files/MouseLocator.dmg -O mouselocator.dmg
	hdiutil	mount mouselocator.dmg
	cp -r /Volumes/Mouse*/Mouse*.app/Contents/Resources/Distribution/MouseLocator.prefPane ~/Library/PreferencePanes/
	hdiutil unmount -force /Volumes/Mouse*
	rm mouselocator.dmg
	# brew cask for prey requires API key
	wget --no-check-certificate -nd -r -l1 --no-parent -A dmg https://preyproject.com/releases/current/ && rm robots.txt && mv prey*.dmg ~/Desktop
	# brew cask installation of alfred doesn't work well with app symlinks
	wget --no-check-certificate --user-agent "safari" -A dmg http://www.macupdate.com/download/34344 -O alfred.zip
	unzip alfred.zip
	mv Alfred* /Applications/
	rm alfred.zip
fi

echo -n  -e "\033[1;31mInstall apps for your personal computer? \033[0;32m(y/n): \033[0m"
read -n 1 home
echo""
if [ "$home" == "y" ]; then
	brew cask install flux
	brew cask install transmission
	brew cask install picasa
	brew cask install teamviewer
	brew cask install tvshows
	brew cask install skydrive
	brew cask install google-drive
	brew cask install copy
	brew cask install google-hangouts
fi

echo -n  -e "\033[1;31mInstall dev apps? \033[0;32m(y/n): \033[0m"
read -n 1 dev
echo ""
if [ "$dev" == "y" ]; then
	brew install chromedriver
	brew cask install virtualbox
	sudo easy_install nose
	sudo easy_install bpython
	sudo pip install -U selenium
	sudo pip install -U holmium.core
	sudo pip install flake8
	#brew cask install vagrant
	#brew cask install mongohub
	#brew cask install sequel-pro
	#\curl -L https://get.rvm.io | bash -s stable --ruby
	#/bin/bash --login -c "rvm reload && gem install bundler"
	#vagrant plugin install vagrant-omnibus
	#vagrant plugin install vagrant-berkshelf
	#/bin/bash --login -c "rvm reload && gem install bundler"
	#/bin/bash --login -c "rvm reload && gem install berkshelf"
	#brew cask install java
fi

echo -n -e "\033[1;31mdotfiles in /Volumes/Stuff/repo/dotfiles/? \033[0;32m(y/n): \033[0m"
read -n 1 sym
echo ""
if [ "$sym" == "y" ]; then
	rm ~/.vim
	ln -s /Volumes/Stuff/repo/dotfiles/.vim ~/.vim
	rm ~/.vimrc
	ln -s /Volumes/Stuff/repo/dotfiles/.vimrc ~/.vimrc
	rm ~/.bash_profile
	ln -s /Volumes/Stuff/repo/dotfiles/.bash_profile ~/.bash_profile
	rm ~/.bashrc
	rm ~/.gitconfig
	ln -s /Volumes/Stuff/repo/dotfiles/.gitconfig ~/.gitconfig
	rm ~/.gitignore_global
	ln -s /Volumes/Stuff/repo/dotfiles/.gitignore_global ~/.gitignore_global
	rm ~/.gitflow_export
	ln -s /Volumes/Stuff/repo/dotfiles/.gitflow_export ~/.gitflow_export
	rm ~/.ssh
	ln -s /Volumes/Stuff/repo/dotfiles/.ssh/ ~/.ssh
	/bin/bash --login -c 'sudo chmod 700 ~/.ssh/*'
	ln -s /Volumes/Stuff/Cloud/Dropbox/ ~/Dropbox
	ln -s /Volumes/Stuff/repo/ ~/repo
	ln -s /Volumes/Stuff/repo/android_sdk/ ~/android_sdk
	ln -s /Volumes/Stuff/vagrant/ ~/vagrant
	/bin/bash --login -c ". ~/.bash_profile"
fi
echo -e "Cleanup and link brew cask to alfred"
brew cleanup && brew cask cleanup
rm -f -r /Library/Caches/Homebrew/*
brew cask alfred link
echo""
echo "***************************************************************************************************************************************"
echo -e "                       To change hostname, run this ---> \033[1;31msudo scutil --set HostName <hostname>\033[0m"
echo -e "       Mouse Locator Agent lives here ----> \033[1;31m/Users/sajnikanth/Library/PreferencePanes/MouseLocator.prefPane/Contents/Resources/\033[0m"
echo -e "      enable hot corners, dock animation, install app from anywhere, turn on firewall, turn off Auto Sleep, keyboard repeat fast\033[0m"
echo -e "     keyboard tab for all controls, set alt+space to spotlight, mouse, touchpad, user image, show date, change textdit preference\033[0m"
echo "***************************************************************************************************************************************"
echo ""
